const texts = {
    en: {
        titleApp: "Emergency Digital Location",
        heroTitle: "Share Your Exact Location Instantly",
        heroSubtitle: "Revolutionary emergency app using Google Plus Codes for precise location sharing when every second counts",
        betaNotice: "⚠️ This app is in beta. Join our testers group to help us improve! ⚠️",
        betaButton: "Join Beta Testers Group",
        demoLocationLabel: "Your location becomes:",
        demoAccuracy: "3-meter accuracy • Works anywhere",
        copyButton: "Copy",
        shareButton: "Share",
        exampleDesign: "* Sample App Design *",
        featuresTitle: "Why Emergency Digital Location?",
        featuresSubtitle: "Purpose-built for emergency situations where precise location sharing can save lives",
        features: [
            { title: "Instant Location", desc: "Generate your precise Plus Code in seconds. No typing addresses or explaining directions." },
            { title: "3-Meter Precision", desc: "Google Plus Codes provide exact location accuracy down to 3 meters anywhere in the world." },
            { title: "Privacy First", desc: "Your location is processed only on your device. No data storage or sharing with third parties." },
            { title: "Works Everywhere", desc: "Rural areas, foreign countries, places without traditional addresses - Plus Codes work anywhere." },
            { title: "Simple Interface", desc: "Designed for stress situations. Large buttons, clear text, intuitive actions when you need them most." },
            { title: "Emergency Ready", desc: "Compatible with Google Maps and emergency services worldwide. Responders know Plus Codes." }
        ],
        howItWorksTitle: "How It Works",
        howItWorksSubtitle: "Three simple steps to share your exact location in any emergency",
        step1Title: "Tap Location Button",
        step1Desc: "Open the app and tap \"Get My Location\" - your GPS coordinates are instantly captured",
        step2Title: "Plus Code Generated",
        step2Desc: "Your location is converted to a short, shareable Plus Code like \"8CMV2FJW+VC\"",
        step3Title: "Share Instantly",
        step3Desc: "Copy or share your Plus Code via text, call, or any messaging app. Responders can find you exactly",
        ctaTitle: "Ready for Any Emergency?",
        ctaSubtitle: "Download Emergency Digital Location now and have precise location sharing at your fingertips",
        builtCodes: "Built with Google Plus Codes technology.",
        comingSoon: "Coming Soon",
        contactUs: "Contact Us",
        privacyPolicy: "Privacy Policy",
        supportTitle: "☕ Buy Me A Coffee",
        joinTelegram: "Join on Telegram",
        launchGPlay: "🎉 Google Play Launch: September 21 🎉"
    },
    es: {
        titleApp: "Ubicación Digital Emergencia",
        heroTitle: "Tu ubicación exacta al instante",
        heroSubtitle: "App de emergencia revolucionaria usando Google Plus Codes para compartir tu ubicación precisa cuando cada segundo cuenta",
        betaNotice: "⚠️ Esta app está en fase de pruebas. ¡Únete para ayudarnos a mejorar! ⚠️",
        betaButton: "Únete al grupo de testers",
        demoLocationLabel: "Tu ubicación será:",
        demoAccuracy: "Precisión de 3 metros • Funciona en cualquier lugar",
        copyButton: "Copiar",
        shareButton: "Compartir",
        exampleDesign: "* Ejemplo Diseño App *",
        featuresTitle: "¿Por qué Ubicación Digital Emergencia?",
        featuresSubtitle: "Diseñada específicamente para situaciones de emergencia donde compartir tu ubicación precisa puede salvar vidas",
        features: [
            { title: "Ubicación instantánea", desc: "Genera tu Plus Code preciso en segundos. No hace falta escribir direcciones ni explicarlas." },
            { title: "Precisión de 3 metros", desc: "Google Plus Codes proporcionan una ubicación exacta con precisión de hasta 3 metros en cualquier lugar del mundo." },
            { title: "Privacidad ante todo", desc: "Tu ubicación se procesa únicamente en tu dispositivo. Sin almacenamiento ni compartir datos con terceros." },
            { title: "Funciona en cualquier lugar", desc: "Áreas rurales, países extranjeros, lugares sin direcciones tradicionales - Plus Codes funcionan en cualquier lugar." },
            { title: "Interfaz sencilla", desc: "Diseñada para situaciones de estrés. Botones grandes, texto claro, acciones intuitivas cuando más las necesitas." },
            { title: "Preparada para emergencias", desc: "Compatible con Google Maps y servicios de emergencia en todo el mundo. Los equipos de rescate conocen los Plus Codes." }
        ],
        howItWorksTitle: "Cómo funciona",
        howItWorksSubtitle: "Tres pasos sencillos para compartir tu ubicación exacta en cualquier emergencia",
        step1Title: "Pulsa el botón de ubicación",
        step1Desc: "Abre la app y toca \"Obtener mi ubicación\" – tus coordenadas GPS se capturan al instante",
        step2Title: "Generación del Plus Code",
        step2Desc: "Tu ubicación se convierte en un Plus Code corto y fácil de compartir, como \"8CMV2FJW+VC\"",
        step3Title: "Comparte al instante",
        step3Desc: "Copia o comparte tu Plus Code por SMS, llamada o cualquier app de mensajería. Los equipos de rescate podrán localizarte exactamente",
        ctaTitle: "¿Listo para cualquier emergencia?",
        ctaSubtitle: "Descarga Ubicación Digital Emergencia ahora y tendrás el envío de ubicación precisa al alcance de tu mano",
        builtCodes: "Implementado con la tecnología de Google Plus Codes.",
        comingSoon: "Próximamente",
        contactUs: "Contáctanos",
        privacyPolicy: "Política de Privacidad",
        supportTitle: "☕ Apóyame con un café",
        joinTelegram: "Únete al canal de Telegram",
        launchGPlay: "🎉 Lanzamiento Google Play: 21 Septiembre 🎉"

    }
};