name: Build and Deploy Site with Jekyll Blog
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Permite ejecutar manualmente

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
        working-directory: blog
    
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v4
    
    - name: Build Jekyll blog
      run: |
        cd blog
        bundle exec jekyll build --destination ../_site/blog --baseurl "${{ steps.pages.outputs.base_path }}/blog"
      env:
        JEKYLL_ENV: production
    
    - name: Copy landing page files
      run: |
        # Copiar todos los archivos estáticos de tu landing
        cp index.html _site/
        cp styles.css _site/
        cp -r assets _site/
        cp -r es _site/
        cp CNAME _site/
        cp robots.txt _site/
        cp sitemap.xml _site/
        cp site.webmanifest _site/
        
        # Debug: mostrar lo que se copió
        echo "=== Archivos en _site ==="
        ls -la _site/
        echo "=== Archivos en _site/blog ==="
        ls -la _site/blog/ || echo "Blog directory not found"
    
    - name: Upload site artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
